In [1]:
import pandas as pd
import numpy as np
import math


data = pd.read_table("student-mat.csv",sep=";",header=0)
data

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [2]:
numerical  = ['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']
categorical = []

for f in data.columns:
    if f not in numerical:
        categorical.append(f)
    else:
        v = data[f].value_counts().sort_index()
        print(f'{f} = {v.index.values}')
    
print(f'numerical = {numerical}')
# print(f'categorical = {categorical}')

age = [15 16 17 18 19 20 21 22]
Medu = [0 1 2 3 4]
Fedu = [0 1 2 3 4]
traveltime = [1 2 3 4]
studytime = [1 2 3 4]
failures = [0 1 2 3]
famrel = [1 2 3 4 5]
freetime = [1 2 3 4 5]
goout = [1 2 3 4 5]
Dalc = [1 2 3 4 5]
Walc = [1 2 3 4 5]
health = [1 2 3 4 5]
absences = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 28 30 38 40 54 56 75]
G1 = [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
G2 = [ 0  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
G3 = [ 0  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
numerical = ['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

In [3]:
class Counter(dict):
    def __init__(self, c=None):
        if c is not None:
            for k, v in c.items():
                self.increment(k, v)
        
    def increment(self, k, v=1):
        o = self.get(k)
        if o == None:
            self[k] = v
        else:
            self[k] = o + v
            
    def get(self, k):
        r = super().get(k)
        if r == None:
            r = 0
        return r
    
    def scale(self, c):
        for k, v in self.items():
            self[k] = v * c * 1.0
    
    def sum(self):
        r = 0
        for k, v in self.items():
            r += v
        return r
    
    def normalize(self):
        self.scale(1.0 / self.sum())

In [4]:
c = Counter()
print(c)
c.increment('a', 1)
print(c)
c.increment('a')
print(c)
c.increment('b', 2)
c.increment('c', 3)
print(c)
print()

for k, v in c.items():
    print(f'k={k}, v={v}')

{}
{'a': 1}
{'a': 2}
{'a': 2, 'b': 2, 'c': 3}

k=a, v=2
k=b, v=2
k=c, v=3

### 문제 1

In [5]:
def get_occurrences(f): 
    """
    Returns:
        _type_: dictionary, [key(scalar): value(list)]
    """
    r = {}
    x = data[f]
    for i, v in enumerate(x.values):
        o = r.get(v)
        if o == None:
            o = []
            r[v] = o
        o.append(i)
    return r

def get_value_counts(f):
    """
    Returns:
        _type_: dictionary, [key(scalar): value(scalar)]
    """
    
    r = Counter() # 필요시 사용 (사용하지 않아도 됨)
    for k, v in get_occurrences(f).items():
        r.increment(k,len(v))
    return r

column_name1 = 'age'
column_name2 = 'studytime'

print(f"Occurrences for each value of '{column_name1}': ", get_occurrences(column_name1))
print(f"Occurrences for each value of '{column_name2}': ", get_occurrences(column_name2))
# print(print(type(get_occurrences(column_name1))))

print(f"Num of occurrences for each value of '{column_name1}': ", get_value_counts(column_name1))
print(f"Num of occurrences for each value of '{column_name2}': ", get_value_counts(column_name2))

Occurrences for each value of 'age':  {18: [0, 128, 150, 157, 213, 217, 223, 225, 228, 239, 244, 248, 250, 252, 258, 260, 261, 262, 264, 265, 267, 268, 269, 271, 272, 276, 277, 278, 279, 282, 283, 286, 288, 289, 290, 292, 294, 297, 298, 299, 300, 305, 316, 317, 319, 325, 330, 332, 333, 334, 338, 341, 342, 344, 345, 346, 347, 349, 352, 355, 358, 359, 360, 361, 362, 365, 366, 368, 369, 371, 374, 375, 377, 378, 380, 381, 384, 385, 386, 388, 389, 393], 17: [1, 7, 18, 78, 118, 132, 136, 144, 154, 156, 160, 163, 164, 172, 175, 177, 179, 182, 183, 185, 188, 189, 191, 192, 195, 196, 198, 202, 203, 205, 209, 211, 214, 215, 216, 218, 219, 220, 221, 226, 227, 229, 230, 231, 232, 236, 238, 240, 241, 246, 254, 255, 256, 259, 263, 266, 273, 274, 275, 280, 281, 284, 285, 287, 291, 293, 295, 301, 302, 303, 318, 320, 321, 322, 323, 324, 326, 327, 328, 329, 331, 335, 337, 339, 343, 348, 351, 354, 356, 357, 363, 364, 367, 372, 373, 379, 382, 391], 15: [2, 3, 8, 9, 10, 11, 12, 13, 14, 20, 21, 24, 26, 27, 30, 31, 32, 33, 35, 36, 38, 39, 41, 42, 43, 45, 48, 49, 51, 52, 53, 54, 56, 57, 58, 64, 66, 68, 69, 71, 72, 75, 76, 80, 81, 82, 83, 84, 85, 87, 91, 94, 95, 102, 103, 104, 105, 106, 108, 110, 113, 114, 116, 119, 120, 121, 125, 126, 130, 131, 134, 135, 139, 140, 142, 145, 146, 147, 149, 152, 155, 161], 16: [4, 5, 6, 15, 16, 17, 19, 22, 23, 25, 28, 29, 34, 37, 40, 44, 46, 47, 50, 55, 59, 60, 61, 62, 63, 65, 67, 70, 73, 74, 77, 79, 86, 88, 89, 90, 92, 93, 96, 97, 98, 99, 100, 101, 107, 109, 111, 112, 115, 117, 122, 123, 124, 129, 133, 137, 138, 141, 143, 148, 151, 158, 159, 162, 165, 166, 167, 168, 169, 170, 171, 173, 174, 176, 178, 180, 181, 184, 186, 187, 190, 193, 194, 197, 199, 200, 201, 204, 206, 207, 208, 212, 222, 224, 233, 234, 235, 237, 242, 243, 245, 249, 251, 253], 19: [127, 153, 210, 257, 270, 296, 304, 307, 308, 309, 310, 311, 312, 313, 314, 315, 336, 340, 350, 353, 370, 383, 387, 394], 22: [247], 20: [306, 376, 390], 21: [392]}
Occurrences for each value of 'studytime':  {2: [0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 13, 17, 20, 22, 23, 28, 29, 30, 31, 32, 33, 40, 42, 44, 45, 46, 48, 49, 50, 51, 55, 56, 57, 58, 59, 60, 62, 64, 65, 68, 72, 74, 75, 79, 82, 83, 84, 85, 86, 88, 89, 92, 93, 97, 103, 104, 112, 114, 115, 116, 118, 120, 122, 124, 126, 127, 134, 136, 138, 145, 146, 147, 155, 159, 161, 164, 166, 167, 168, 169, 171, 172, 173, 174, 175, 176, 177, 179, 180, 181, 182, 183, 184, 185, 187, 188, 189, 190, 191, 192, 195, 199, 200, 201, 202, 206, 207, 211, 212, 213, 215, 216, 217, 220, 222, 223, 225, 226, 227, 228, 230, 231, 232, 233, 234, 236, 238, 239, 240, 241, 248, 251, 257, 258, 260, 261, 265, 266, 267, 268, 269, 270, 272, 273, 274, 275, 276, 278, 283, 284, 285, 289, 290, 292, 296, 297, 300, 304, 305, 308, 309, 310, 311, 312, 313, 316, 319, 320, 321, 332, 333, 337, 339, 341, 342, 343, 350, 351, 354, 355, 356, 357, 360, 361, 362, 363, 364, 365, 369, 370, 377, 378, 379, 380, 382, 388, 389, 390], 3: [3, 11, 14, 16, 24, 36, 37, 38, 63, 81, 87, 90, 99, 101, 107, 109, 111, 130, 135, 142, 152, 205, 209, 219, 221, 224, 229, 235, 244, 262, 263, 264, 286, 287, 288, 291, 294, 302, 314, 315, 317, 318, 322, 323, 324, 325, 328, 329, 331, 335, 336, 340, 344, 345, 346, 347, 348, 359, 366, 372, 374, 375, 376, 385, 387], 1: [12, 15, 18, 19, 21, 25, 26, 27, 34, 35, 39, 41, 43, 52, 53, 54, 61, 73, 78, 80, 91, 96, 98, 100, 102, 110, 113, 117, 119, 123, 125, 128, 129, 131, 132, 133, 137, 139, 141, 143, 144, 148, 149, 150, 151, 153, 154, 156, 157, 158, 160, 162, 163, 165, 170, 178, 186, 193, 194, 196, 197, 198, 203, 208, 214, 218, 237, 242, 243, 245, 246, 247, 249, 250, 252, 253, 254, 255, 277, 279, 280, 281, 295, 299, 301, 306, 307, 326, 327, 349, 352, 353, 358, 367, 368, 371, 373, 381, 383, 384, 386, 391, 392, 393, 394], 4: [47, 66, 67, 69, 70, 71, 76, 77, 94, 95, 105, 106, 108, 121, 140, 204, 210, 256, 259, 271, 282, 293, 298, 303, 330, 334, 338]}
Num of occurrences for each value of 'age':  {18: 82, 17: 98, 15: 82, 16: 104, 19: 24, 22: 1, 20: 3, 21: 1}
Num of occurrences for each value of 'studytime':  {2: 198, 3: 65, 1: 105, 4: 27}

### extra problem

In [6]:
pair = {'age' : 18, 'studytime' : 2}


def get_co_occurrences(pair):
    """
    Returns:
        _type_: list
    """
    keys = list(pair.keys())
    
    r = []
    x = data[keys[0]]
    y = data[keys[1]]
    # print(y[1])
    for i, v in enumerate(x.values):
        if v == 18 and y[i] == 2:
            r.append(i)
    return r

print(f"Co_occurrences of {pair}: ", get_co_occurrences(pair)) 
print(f"Num of co_occurrences of {pair}: ", len(get_co_occurrences(pair)))

Co_occurrences of {'age': 18, 'studytime': 2}:  [0, 213, 217, 223, 225, 228, 239, 248, 258, 260, 261, 265, 267, 268, 269, 272, 276, 278, 283, 289, 290, 292, 297, 300, 305, 316, 319, 332, 333, 341, 342, 355, 360, 361, 362, 365, 369, 377, 378, 380, 388, 389]
Num of co_occurrences of {'age': 18, 'studytime': 2}:  42

### 문제 2

In [26]:
def get_pmf(f):
    """
    Returns:
        _type_: dictionary [key(scalar): value(scalar)]
    """
    r = get_value_counts(f)
    # print(r)
    r.normalize() # 확률을 구해주는 식
    return r

def get_mean(f):
    """
    Returns:
        _type_: scalar
    """
    r = 0.0
    count_r = 0
    for k, v in get_value_counts(f).items():
        r += k * v
        count_r += v
    return r / count_r

def get_variance(f):
    """
    Returns:
        _type_: scalar
    """
    r = 0.0
    count = 0
    for k, v in get_value_counts(f).items():
        count += v
        r += math.pow(v - get_mean(f), 2)
    return r / count

for f in numerical:
    print(f'{f} = {get_mean(f)} {get_variance(f)} {get_pmf(f)}')

age = 16.696202531645568 59.481279574232474 {18: 0.20759493670886076, 17: 0.24810126582278483, 15: 0.20759493670886076, 16: 0.26329113924050634, 19: 0.06075949367088608, 22: 0.002531645569620253, 20: 0.00759493670886076, 21: 0.002531645569620253}
Medu = 2.749367088607595 98.54884834668252 {4: 0.33164556962025316, 1: 0.14936708860759493, 3: 0.25063291139240507, 2: 0.2607594936708861, 0: 0.00759493670886076}
Fedu = 2.5215189873417723 94.19946908865221 {4: 0.24303797468354432, 1: 0.20759493670886076, 2: 0.2911392405063291, 3: 0.25316455696202533, 0: 0.005063291139240506}
traveltime = 1.4481012658227848 194.8237670610236 {2: 0.2708860759493671, 1: 0.6506329113924051, 3: 0.05822784810126582, 4: 0.020253164556962026}
studytime = 2.0354430379746837 135.67486610998318 {2: 0.5012658227848101, 3: 0.16455696202531647, 1: 0.2658227848101266, 4: 0.06835443037974684}
failures = 0.3341772151898734 253.48214353834078 {0: 0.789873417721519, 3: 0.04050632911392405, 2: 0.043037974683544304, 1: 0.12658227848101267}
famrel = 3.9443037974683546 129.70832319552812 {4: 0.4936708860759494, 5: 0.2683544303797468, 3: 0.17215189873417722, 1: 0.020253164556962026, 2: 0.04556962025316456}
freetime = 3.2354430379746835 104.87934293230353 {3: 0.39746835443037976, 2: 0.1620253164556962, 4: 0.2911392405063291, 1: 0.04810126582278481, 5: 0.10126582278481013}
goout = 3.108860759493671 90.72234196483444 {4: 0.21772151898734177, 3: 0.32911392405063294, 2: 0.2607594936708861, 1: 0.05822784810126582, 5: 0.1341772151898734}
Dalc = 1.481012658227848 206.278397449289 {1: 0.6987341772151899, 2: 0.189873417721519, 5: 0.02278481012658228, 3: 0.06582278481012659, 4: 0.02278481012658228}
Walc = 2.2911392405063293 96.27151036733402 {1: 0.3822784810126582, 3: 0.20253164556962025, 2: 0.21518987341772153, 4: 0.1291139240506329, 5: 0.07088607594936709}
health = 3.5544303797468353 89.72701234587934 {3: 0.23037974683544304, 5: 0.369620253164557, 1: 0.1189873417721519, 2: 0.11392405063291139, 4: 0.1670886075949367}
absences = 5.708860759493671 48.544549619806986 {6: 0.07848101265822785, 4: 0.1341772151898734, 10: 0.043037974683544304, 2: 0.16455696202531647, 0: 0.2911392405063291, 16: 0.017721518987341773, 14: 0.03037974683544304, 7: 0.017721518987341773, 8: 0.05569620253164557, 25: 0.002531645569620253, 12: 0.03037974683544304, 54: 0.002531645569620253, 18: 0.012658227848101266, 26: 0.002531645569620253, 20: 0.010126582278481013, 56: 0.002531645569620253, 24: 0.002531645569620253, 28: 0.002531645569620253, 5: 0.012658227848101266, 13: 0.00759493670886076, 15: 0.00759493670886076, 22: 0.00759493670886076, 3: 0.020253164556962026, 21: 0.002531645569620253, 1: 0.00759493670886076, 75: 0.002531645569620253, 30: 0.002531645569620253, 19: 0.002531645569620253, 9: 0.00759493670886076, 11: 0.00759493670886076, 38: 0.002531645569620253, 40: 0.002531645569620253, 23: 0.002531645569620253, 17: 0.002531645569620253}
G1 = 10.90886075949367 16.648240840988237 {5: 0.017721518987341773, 7: 0.09367088607594937, 15: 0.06075949367088608, 6: 0.06075949367088608, 12: 0.08860759493670886, 16: 0.05569620253164557, 14: 0.0759493670886076, 10: 0.1291139240506329, 13: 0.08354430379746836, 8: 0.10379746835443038, 11: 0.09873417721518987, 9: 0.07848101265822785, 17: 0.020253164556962026, 19: 0.00759493670886076, 18: 0.020253164556962026, 4: 0.002531645569620253, 3: 0.002531645569620253}
G2 = 10.713924050632912 16.370630039408645 {6: 0.035443037974683546, 5: 0.0379746835443038, 8: 0.0810126582278481, 14: 0.05822784810126582, 10: 0.11645569620253164, 15: 0.08607594936708861, 12: 0.10379746835443038, 18: 0.03037974683544304, 16: 0.03291139240506329, 13: 0.09367088607594937, 9: 0.12658227848101267, 11: 0.08860759493670886, 7: 0.053164556962025315, 19: 0.00759493670886076, 17: 0.012658227848101266, 4: 0.002531645569620253, 0: 0.03291139240506329}
G3 = 10.415189873417722 17.416636055159934 {6: 0.0379746835443038, 10: 0.14177215189873418, 15: 0.08354430379746836, 11: 0.1189873417721519, 19: 0.012658227848101266, 9: 0.07088607594936709, 12: 0.07848101265822785, 14: 0.06835443037974684, 16: 0.04050632911392405, 5: 0.017721518987341773, 8: 0.0810126582278481, 17: 0.01518987341772152, 18: 0.03037974683544304, 13: 0.07848101265822785, 20: 0.002531645569620253, 7: 0.02278481012658228, 0: 0.09620253164556962, 4: 0.002531645569620253}

### 문제 3

In [42]:
column_name1 = 'studytime'
column_name2 = 'G3' # final grade

def get_covariance(f1, f2):
    """
    Returns:
        _type_: scalar
    """
    s = data[column_name1]
    g = data[column_name2]
    s_mean = get_mean(f1)
    g_mean = get_mean(f2)
    r = 0.0
    for i, j in zip(s,g):
        r += i * j 
        # r += 1
          
    return r / len(data) - s_mean * g_mean

print(f'cov = {get_covariance(column_name1, column_name2)}')
print(f'cov = {data[column_name1].cov(data[column_name2])}') # 정답 값

def get_correlation(f1, f2):
    """
    Returns:
        _type_: scalar
    """
    r = get_covariance(f1, f2)/math.sqrt(get_variance(f1)/get_variance(f2))
    return r

print(f'cor = {get_correlation(column_name1, column_name2)}')
print(f'cor = {data[column_name1].corr(data[column_name2])}') # 정답 값

cov = 0.3751578272712699
cov = 0.37611000449784726
cor = 0.13441460171324143
cor = 0.09781968965319636

### 문제 4

In [52]:
import math

def binomial_pmf(n, p, k_array):
    probabilities = []
    ### start ###
    for i in k_array:
        probabilities.append(math.comb(n,i) * math.pow(p, i) * math.pow(1 - p, n - i))
    ### end ###
    return probabilities

k_values_a = [i for i in range(201)]
PMF_a = binomial_pmf(200, 0.1, k_values_a)
print(PMF_a)
k_values_b = [i for i in range(101)]
PMF_b = binomial_pmf(100, 0.4, k_values_b)

### PMF_a와 PMF_b를 활용하여 P(A+B>=55) 값 구하기 ###
### start ###
result = 0 
# for i in range(56):
print(result)
### end ###

[7.055079108655367e-10, 1.5677953574789707e-08, 1.7332848674350844e-07, 1.2710755694523952e-06, 6.955607977281162e-06, 3.029553696771351e-05, 0.00010940055016118767, 0.00033688423382968903, 0.0009030369045712498, 0.002140531921946666, 0.004542684412131258, 0.008718283215201406, 0.015256995626602458, 0.02451551434018173, 0.03638413636201575, 0.05012925454322169, 0.06440216729511121, 0.07745097243333637, 0.08749091330432442, 0.09311898375080142, 0.09363631143830586, 0.08917743946505322, 0.08062000840527538, 0.06932541785574406, 0.056808328520679165, 0.044436736976175686, 0.03323260243944764, 0.023796184462814358, 0.016336269492328904, 0.0107656641865156, 0.006818253984793214, 0.00415449167532203, 0.002437878795588275, 0.001379002146999428, 0.0007525926749964198, 0.0003966043938076371, 0.00020197445980944486, 9.947090513137826e-05, 4.7408647767294317e-05, 2.188091435413584e-05, 9.78563114171075e-06, 4.243092093966721e-06, 1.7847927061923509e-06, 7.286750583420969e-07, 2.888938993932051e-07, 1.1127765013664195e-07, 4.166192215260749e-08, 1.5167697426717626e-08, 5.371892838629159e-09, 1.8515367607066489e-09, 6.212934463704533e-10, 2.0303707397727234e-10, 6.46421453474649e-11, 2.005668241388848e-11, 6.0665273967934304e-12, 1.7893191917814966e-12, 5.147842912863433e-13, 1.4450085369441215e-13, 3.958548290862249e-14, 1.0585948348445186e-14, 2.764108735427354e-15, 7.048729015661741e-16, 1.7558661884892153e-16, 4.2735367550531164e-17, 1.016448846253953e-17, 2.3630263776160273e-18, 5.370514494581881e-19, 1.1934476654626403e-19, 2.5936035867080258e-20, 5.51297380749532e-21, 1.146348521876011e-21, 2.332164442001275e-22, 4.642734768798834e-23, 9.045206246670485e-24, 1.7248366266173446e-24, 3.2196950363523762e-25, 5.88394560736911e-26, 1.052827208244978e-26, 1.8446972452155593e-27, 3.165303289962e-28, 5.319468028963918e-29, 8.756325973603157e-30, 1.4119279008926502e-30, 2.23035464933511e-31, 3.4517393382567175e-32, 5.234009976964435e-33, 7.77662981073527e-34, 1.1322296276166297e-34, 1.6154286353621106e-35, 2.2587766187335378e-36, 3.0953605515978114e-37, 4.1573829142339354e-38, 5.4728833049697935e-39, 7.061784909638444e-40, 8.931571930630184e-41, 1.1073059937389468e-41, 1.345684367391081e-42, 1.6031062337763165e-43, 1.8721081868362884e-44, 2.1431541532805993e-45, 2.4050952164593394e-46, 2.645869325037777e-47, 2.8533884877858387e-48, 3.0165272039159883e-49, 3.126101910041142e-50, 3.1757225752798904e-51, 3.1624071766414005e-52, 3.086877202536777e-53, 2.953493619711114e-54, 2.769841111247936e-55, 2.5460155669046687e-56, 2.293707717932134e-57, 2.025198282698015e-58, 1.7523839614299442e-59, 1.4859396164172043e-60, 1.234693787554392e-61, 1.005258351936047e-62, 8.01915494421918e-64, 6.267324485595028e-65, 4.798511744339798e-66, 3.598883808254848e-67, 2.643808123603194e-68, 1.902193458694466e-69, 1.3402989139852603e-70, 9.247582112622317e-72, 6.247255471638188e-73, 4.131782719337426e-74, 2.674994936403933e-75, 1.6950922774087423e-76, 1.0512200169976697e-77, 6.379198393746543e-79, 3.787479962360118e-80, 2.1997989680374427e-81, 1.249676940906818e-82, 6.942649671704544e-84, 3.7713158710493824e-85, 2.002741271390604e-86, 1.0395412925304024e-87, 5.2730355418208826e-89, 2.613334960774538e-90, 1.2651859730733876e-91, 5.981966775760697e-93, 2.761627854224423e-94, 1.2445564533412315e-95, 5.473743660528565e-97, 2.3488861685026797e-98, 9.831715317172555e-100, 4.0129450274173693e-101, 1.5967423907891935e-102, 6.191693088817157e-104, 2.3390840557753697e-105, 8.605901603294224e-107, 3.0825232350980773e-108, 1.0745179033021622e-109, 3.643747579740377e-111, 1.2015224994125973e-112, 3.851033651963454e-114, 1.1991895306892565e-115, 3.626241196880312e-117, 1.0643055923757728e-118, 3.0303145338476867e-120, 8.365257512346962e-122, 2.2376203222327266e-123, 5.796153527255869e-125, 1.4529653150980163e-126, 3.5223401578133726e-128, 8.251800905185277e-130, 1.8666748554644006e-131, 4.074091946450081e-133, 8.571396600026472e-135, 1.7366882000053633e-136, 3.3853571150202013e-138, 6.342077282660584e-140, 1.1405148613647807e-141, 1.966404933387553e-143, 3.2461287789254836e-145, 5.123309310172797e-147, 7.71873342398915e-149, 1.1081827013217879e-150, 1.5133469540086492e-152, 1.9617460514926935e-154, 2.408527994466168e-156, 2.793774840955872e-158, 3.0533058371102433e-160, 3.1344323207049597e-162, 3.0120670949717326e-164, 2.698984852125209e-166, 2.2451448561944695e-168, 1.72499309282081e-170, 1.2169263441416648e-172, 7.828181161145215e-175, 4.553915742376506e-177, 2.3718311158210968e-179, 1.0923804793649267e-181, 4.3795322769498776e-184, 1.4972759921196163e-186, 4.243979569500046e-189, 9.574686000000106e-192, 1.611900000000018e-194, 1.8000000000000198e-197, 1.0000000000000112e-200]
0

In [47]:
# 참고: 시뮬레이션을 통해 측정한 확률

import random

def bernoulli(p):
    sample = 1 if random.random() < p else 0
    return sample

def binomial(n, p):
    successes = 0
    # n번 시행
    for _ in range(n):
        successes += bernoulli(p)
    return successes

n_value_a, n_value_b = 200, 100
p_value_a, p_value_b = 0.1, 0.4
data_a = [binomial(n_value_a, p_value_a) for _ in range(10000)]
data_b = [binomial(n_value_b, p_value_b) for _ in range(10000)]
data = [a+b for a, b in zip(data_a, data_b)]

# print(f'data_a: {data_a[:10]}')
# print(f'data_b: {data_b[:10]}')
# print(f'data: {data[:10]}')

mask = [1 if d >= 55 else 0 for d in data]

print(f'P(A+B>=55)={sum(mask)/len(data)}')

P(A+B>=55)=0.8038